// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login', async function() {
    await driver.get("https://www.d3a.io/")
    await driver.manage().window().setRect(2560, 1415)
    await driver.findElement(By.css(".button__label")).click()
    await driver.findElement(By.id("email")).sendKeys("holospin.gabriel@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("Password123!")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.css(".button")).click()
    await driver.findElement(By.css(".icon-cog > use")).click()
    await driver.findElement(By.css(".context-menu--options-button:nth-child(2) > p")).click()
  })
})
