// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Simulation', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Simulation', async function() {
    await driver.get("https://www.d3a.io/")
    await driver.manage().window().setRect(2560, 1415)
    await driver.findElement(By.css(".button__label")).click()
    await driver.findElement(By.id("email")).sendKeys("holospin.gabriel@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("Password123!")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.css(".button")).click()
    await driver.findElement(By.css(".icon-projects")).click()
    assert(await driver.findElement(By.css("div:nth-child(1) > .ConfigurationListHeadWrapper .saved-project__headline__name__text")).getText() == "vars[\"currentdate\"]")
    await driver.findElement(By.css("div:nth-child(1) > .ConfigurationListHeadWrapper .saved-project__headline__name__text")).click()
    await driver.findElement(By.css(".saved-project__button--new-simulation")).click()
    await driver.findElement(By.id("input-field-name")).click()
    await driver.findElement(By.id("input-field-name")).sendKeys("default simulation ")
    await driver.findElement(By.css(".button")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".button--pink:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css(".header-simulation-button-group--active"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.executeScript("window.scrollTo(0,0)")
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("button > .svg-icon > .icon-cog > use")).click()
    {
      const element = await driver.findElement(By.css("button > .svg-icon > .icon-cog > use"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".context-menu--options-button:nth-child(2) > p")).click()
  })
})
